name: CD
on:
  push:
    branches: [main]
jobs:
  cd:
    permissions:
      contents: read
      packages: write
    uses: book-entry/finance-infra/.github/workflows/reusable-cd.yaml@main
    with:
      java-version: "21"
      service-name: finance-gateway
    secrets:
      server-username: ${{ secrets.PACKAGE_USER }}
      server-password: ${{ secrets.PACKAGES_TOKEN }}
      ZEABUR_API_TOKEN: ${{ secrets.ZEABUR_API_TOKEN }}
      ZEABUR_SERVICE_ID: ${{ secrets.ZEABUR_SERVICE_ID }}
      ZEABUR_ENVIRONMENT_ID: ${{ secrets.ZEABUR_ENV_ID }}
